game.Players.LocalPlayer.Character:FindFirstChild("StartRagdoll"):Destroy()
game.Players.LocalPlayer.Character:FindFirstChild("RagdollMe"):Destroy()
game.Players.LocalPlayer.Character:WaitForChild("Falling down"):Destroy()
game.Players.LocalPlayer.Character:WaitForChild("KillScript"):Destroy()
game.Players.LocalPlayer.Character:WaitForChild("Pushed"):Destroy()
game.Players.LocalPlayer.Character:WaitForChild("FirstPerson"):Destroy()
game.Players.LocalPlayer.Character:WaitForChild("Pushed"):Destroy()

game.Players.LocalPlayer.CharacterAdded:Connect(function(character)
    character:WaitForChild("RagdollMe"):Destroy()
    character:WaitForChild("StartRagdoll"):Destroy()
    character:WaitForChild("Falling down"):Destroy()
    character:WaitForChild("KillScript"):Destroy()
    character:WaitForChild("Pushed"):Destroy()
    character:WaitForChild("FirstPerson"):Destroy()
    character:WaitForChild("Pushed"):Destroy()
end)
